"""empty message

Revision ID: 038f4c8e7424
Revises: de5fd2bdc322
Create Date: 2026-06-24 13:02:07.876786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038f4c8e7424'
down_revision = 'de5fd2bdc322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fromrequirements', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('torequirements', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_column('torequirements')
        batch_op.drop_column('fromrequirements')

    # ### end Alembic commands ###
