"""add loyalty points, boarding pass, country

Revision ID: 23eca5a186ce
Revises: 038f4c8e7424
Create Date: 2026-06-25 03:21:28.813136

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23eca5a186ce'
down_revision = '038f4c8e7424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_in', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('boarding_pass_code', sa.String(length=10), nullable=True))
        batch_op.alter_column('seat_preference',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('special_requests',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=True)

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.alter_column('torequirements',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loyalty_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
        batch_op.drop_column('loyalty_points')

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.alter_column('torequirements',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('special_requests',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
        batch_op.alter_column('seat_preference',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('boarding_pass_code')
        batch_op.drop_column('checked_in')

    # ### end Alembic commands ###
