"""empty message

Revision ID: de5fd2bdc322
Revises: 3b7cfa71e164
Create Date: 2026-06-24 12:30:55.619730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de5fd2bdc322'
down_revision = '3b7cfa71e164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fromcountry', sa.String(length=80), nullable=False),
    sa.Column('tocountry', sa.String(length=80), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('residentcountry', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('residentcountry')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries')
    # ### end Alembic commands ###
